import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";
import { StoreProvider } from "@/lib/store/provider";
import { AuthInitializer } from "./_components/auth/AuthInitializer";
import { OnboardingBanner } from "@/components/OnboardingBanner";
import { Header } from "./_components/Header";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className={`${inter.className} antialiased min-h-screen flex flex-col`}>
        <StoreProvider>
          <AuthInitializer>
            <Header />
            <OnboardingBanner />
            {children}
            <Toaster />
          </AuthInitializer>
        </StoreProvider>
        <Script 
          src="https://checkout.razorpay.com/v1/checkout.js" 
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
